name: Transformation
favicon: null
layout_spectrum: 1
typography_spectrum: 0
collections:
  - filter:
      notType:
        type: WebPage
    index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
  - filter:
      type:
        type: Article
    permalink:
      path: '/:title/'
  - filter:
      type:
        type: WebPage
    permalink:
      path: '/:title/'
      navigable: true
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#452b18'
    - '#d1cbc4'
    - '#837163'
    - '#a2958d'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 1
purpose:
  - name: follow
    url: null
    item: 1d591f0a-7644-495c-b0bb-58f30eef3314
